apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nession

images:
  - name: ghcr.io/BestNathan/nession-server
    newTag: main
  - name: ghcr.io/bestnathan/nession-agent
    newTag: main

resources:
  # ── 共用 ──
  - namespace.yaml
  - secret.yaml
  # ── Server 套件 ──
  - deployment-server.yaml
  - service-server.yaml
  - ingress-server.yaml
  # ── Agent 套件 ──
  - deployment-agent.yaml
  - service-agent.yaml
  - ingress-agent.yaml
