apiVersion: v1
kind: Service
metadata:
  name: nession-server
  namespace: nession
spec:
  selector:
    app: nession
    component: server
  ports:
    - name: http
      port: 10080
      targetPort: 10080
    - name: server-ws
      port: 18080
      targetPort: 18080
  type: ClusterIP
