apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nession

commonLabels:
  env: production

resources:
- ../../base

images:
- name: ghcr.io/bestnathan/nession-agent
  newName: ghcr.io/bestnathan/nession
  newTag: agent-0.20.1
- name: ghcr.io/bestnathan/nession-server
  newName: ghcr.io/bestnathan/nession
  newTag: server-0.20.1
- name: ghcr.io/bestnathan/nession-ui
  newName: ghcr.io/bestnathan/nession
  newTag: ui-0.20.1

# Isolate production data on shared PVC via subPath.
patches:
- path: patch-imagepullsecrets.yaml
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/0/subPath
      value: production
  target:
    kind: Deployment
    name: nession-server
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/1/subPath
      value: production
  target:
    kind: Deployment
    name: nession-agent
