apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nession

commonLabels:
  env: production

resources:
- ../../base

images:
- name: ghcr.io/bestnathan/nession-agent
  newName: ghcr.io/bestnathan/nession
  newTag: agent-b55316f
- name: ghcr.io/bestnathan/nession-server
  newName: ghcr.io/bestnathan/nession
  newTag: server-b55316f
- name: ghcr.io/bestnathan/nession-ui
  newName: ghcr.io/bestnathan/nession
  newTag: ui-b55316f
