apiVersion: apps/v1
kind: Deployment
metadata:
  name: nession-server
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nession-agent
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nession-ui
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
