apiVersion: v1
kind: PersistentVolume
metadata:
  name: nession-nfs
  labels:
    app: nession
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    server: 192.168.2.105
    path: /mnt/share/k8s
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
