apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nession-server-data
  labels:
    app: nession
    component: server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
