apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nession

nameSuffix: -staging

commonLabels:
  env: staging

resources:
- ../../base

images:
- name: ghcr.io/bestnathan/nession-agent
  newName: ghcr.io/bestnathan/nession
  newTag: agent-dd33be9
- name: ghcr.io/bestnathan/nession-server
  newName: ghcr.io/bestnathan/nession
  newTag: server-dd33be9
- name: ghcr.io/bestnathan/nession-ui
  newName: ghcr.io/bestnathan/nession
  newTag: ui-dd33be9

patches:
- path: patch-ingress.yaml
- path: patch-agent-env.yaml
