apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nession

nameSuffix: "-staging"

commonLabels:
  env: staging

resources:
  - ../../base

images:
  - name: ghcr.io/bestnathan/nession-server
    newName: ghcr.io/bestnathan/nession
    newTag: server-ccd7c9a
  - name: ghcr.io/bestnathan/nession-agent
    newName: ghcr.io/bestnathan/nession
    newTag: agent-ccd7c9a
  - name: ghcr.io/bestnathan/nession-ui
    newName: ghcr.io/bestnathan/nession
    newTag: ui-ccd7c9a

patches:
  - path: patch-ingress.yaml
  - path: patch-agent-env.yaml
